### ISSUE TITLE
Improve user experience when hitting cache [Tracker]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1112]
**Is your feature request related to a problem? Please describe.**
Currently, some stacks take some time to produce recommendations. The idea is to pre-heat some most common stacks to give the possibility to users to receive recommendations faster. 

At the same time a mechanism to invalidate the cache needs to be kept in place so that users can receive always the most updated stacks:

- [x] timeout
- [x] force parameter 

**Describe the solution you'd like**
In order to implement this feature the following tasks are required:

- [x] token for authenticated request https://github.com/thoth-station/user-api/pull/1336 
- [x] Remove origin from digest definition for unauthenticated users https://github.com/thoth-station/user-api/pull/1354
- [x] Introduce parameter to allow optionally to run only some parts of adviser workflow https://github.com/thoth-station/thoth-application/issues/945 
- [x] Introduce monitor cache hit rates in user-api for different type of users https://github.com/thoth-station/user-api/issues/1345 
- [x] Introduce monitor of workflow task latency https://github.com/thoth-station/slo-reporter/issues/236

**Describe alternatives you've considered**
Leave the services as they are.

**Additional context**

Related-To: https://github.com/thoth-station/thoth-application/issues/1025

@goern @harshad16 @fridex @KPostOffice

**Comment by fridex** [comment]
> * [ ]  Remove origin from parameters so that adviser ID does not include that when generating hash and cache can be hit by different users requesting same stack (only privileged user will provide origin to track users)

Do not remove the origin parameter from the request. It can still be part of the request (and we want to have it to track requests).

> * [ ]  [Optional] Change integrations tests to run every some time to invalidate cache and recompute new results (~2 hours?)

This should be in sync with user-api cache expiration configuration.

https://github.com/thoth-station/thoth-application/blob/f0b7f1a46f7c84b793843c515afb0942137039be/user-api/base/configmap.yaml#L9

> * [ ]  [Longterm/Auotmation] Automate the cache invalidation using internal triggers for monitored stacked (new package release, new cve, new…)
> * [ ]  [Longterm/Optimization] Introduce average time of release for software stacks (including transitive dependencies) to identify specific cache invalidation time for software stacks

How do you want to accomplish these?

**Comment by goern** [comment]
@pacospace could you please track this?

/assign @pacospace

**Comment by pacospace** [comment]
> > * [ ]   Remove origin from parameters so that adviser ID does not include that when generating hash and cache can be hit by different users requesting same stack (only privileged user will provide origin to track users)
> 
> Do not remove the origin parameter from the request. It can still be part of the request (and we want to have it to track requests).

Sorry, then remove from the digest generation? https://github.com/thoth-station/user-api/blob/494b44eae3ef80e6a17d284977db03c63b688130/thoth/user_api/api_v1.py#L109

> 
> > * [ ]   [Optional] Change integrations tests to run every some time to invalidate cache and recompute new results (~2 hours?)
> 
> This should be in sync with user-api cache expiration configuration.
> 
> https://github.com/thoth-station/thoth-application/blob/f0b7f1a46f7c84b793843c515afb0942137039be/user-api/base/configmap.yaml#L9
> 

I think this solution could be combined at some point also, or one or the other can be selected.

> > * [ ]   [Longterm/Auotmation] Automate the cache invalidation using internal triggers for monitored stacks (new package release, new cve, new…)

we need to have a list of monitored stacks that we "maintain" (we can have a cronworkflow that analyze adviser reports, create statistics and update the list of stack automatically every week for example)

Once we have that list we can use messages received by Kafka, we can simply use the consumers in investigator to schedule a new workflow (step 1 take list of known stacks, check which one has the package and step 2 send messages to kafka for scheduling adviser worfklow with force=True, therefore invalidating previous stacks).

> > * [ ]   [Longterm/Optimization] Introduce average time of release for software stacks (including transitive dependencies) to identify specific cache invalidation time for software stacks

This could be an initial data analysis project.
Here we need to have a new parameter per package name -> `average time of release`. 

(first step, we could analyze some stacks and come out with software stack invalidation period (e.g. on average every 2 days this stack might be invalidated based on the packages used and their time of release)
We can add release date to database, then we can have a query to get release dates for one package and evaluate average time. If we don't want this we can have cronworkflow using thoth-python that store these statistics that can be retrieved from Ceph. 


> 
> How do you want to accomplish these?

**Comment by fridex** [comment]
> > > * [ ]    [Longterm/Auotmation] Automate the cache invalidation using internal triggers for monitored stacks (new package release, new cve, new…)
> 
> we need to have a list of monitored stacks that we "maintain" (we can have a cronworkflow that analyze adviser reports, create statistics and update the list of stack automatically every week for example)
> 
> Once we have that list we can use messages received by Kafka, we can simply use the consumers in investigator to schedule a new workflow (step 1 take list of known stacks, check which one has the package and step 2 send messages to kafka for scheduling adviser worfklow with force=True, therefore invalidating previous stacks).
> 
> This is basically similar to what we do with Kebechet administrator for stack of users of Kebechet.
> 
> > > * [ ]    [Longterm/Optimization] Introduce average time of release for software stacks (including transitive dependencies) to identify specific cache invalidation time for software stacks
> 
> This could be an initial data analysis project.
> Here we need to have a new parameter per package name -> `average time of release`.
> 
> We can add release date to database, then we can have a query to get release dates for one package and evaluate average time. If we don't want this in the database we can have cronworkflow using thoth-python that store these statistics that can be retrieved from Ceph.
> 
> we could analyze some stacks and come out with `software stack invalidation period` (e.g. on average every 2 days this stack might be invalidated based on the packages used and their time of release). This could be connected to the list of monitored stacks mentioned above.
> 
> This solution uses processed data, so it is requesting more work but it might be an alternative to the one above using the internal triggers. But the one above seems more easy to implement and more in line with the current architecture.
> 
> > How do you want to accomplish these?

Both of them do not sound like correct approaches to me. I see "long term" tag you added - then let's push back them to deliver a working solution.

**Comment by pacospace** [comment]
> > > > * [ ]     [Longterm/Auotmation] Automate the cache invalidation using internal triggers for monitored stacks (new package release, new cve, new…)
> > 
> > 
> > we need to have a list of monitored stacks that we "maintain" (we can have a cronworkflow that analyze adviser reports, create statistics and update the list of stack automatically every week for example)
> > Once we have that list we can use messages received by Kafka, we can simply use the consumers in investigator to schedule a new workflow (step 1 take list of known stacks, check which one has the package and step 2 send messages to kafka for scheduling adviser worfklow with force=True, therefore invalidating previous stacks).
> > This is basically similar to what we do with Kebechet administrator for stack of users of Kebechet.
> > > > * [ ]     [Longterm/Optimization] Introduce average time of release for software stacks (including transitive dependencies) to identify specific cache invalidation time for software stacks
> > 
> > 
> > This could be an initial data analysis project.
> > Here we need to have a new parameter per package name -> `average time of release`.
> > We can add release date to database, then we can have a query to get release dates for one package and evaluate average time. If we don't want this in the database we can have cronworkflow using thoth-python that store these statistics that can be retrieved from Ceph.
> > we could analyze some stacks and come out with `software stack invalidation period` (e.g. on average every 2 days this stack might be invalidated based on the packages used and their time of release). This could be connected to the list of monitored stacks mentioned above.
> > This solution uses processed data, so it is requesting more work but it might be an alternative to the one above using the internal triggers. But the one above seems more easy to implement and more in line with the current architecture.
> > > How do you want to accomplish these?
> 
> Both of them do not sound like correct approaches to me. I see "long term" tag you added - then let's push back them to deliver a working solution.

We can review them, I can create separate issues for those and we will check in the future if we want to do them or discuss better approaches, wdyt? @fridex

**Comment by pacospace** [comment]
related-to: https://github.com/thoth-station/user-api/issues/1367

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> Currently, some stacks take some time to produce recommendations. The idea is to pre-heat some most common stacks to give the possibility to users to receive recommendations faster.
> 
> At the same time a mechanism to invalidate the cache needs to be kept in place so that users can receive always the most updated stacks:
> 
> * [x]  timeout
> * [x]  force parameter
> * [ ]  integration test retrigger most used stacks
> 
> **Describe the solution you'd like**
> In order to implement this feature the following tasks are required:
> 
> * [x]  token for authenticated request [thoth-station/user-api#1336](https://github.com/thoth-station/user-api/pull/1336)
> * [x]  Remove origin from digest definition for unauthenticated users [thoth-station/user-api#1354](https://github.com/thoth-station/user-api/pull/1354)
> * [x]  Introduce parameter to allow optionally to run only some parts of adviser workflow #945
> * [x]  Introduce monitor cache hit rates in user-api for different type of users [thoth-station/user-api#1345](https://github.com/thoth-station/user-api/issues/1345)
> * [x]  Introduce monitor of workflow task latency [thoth-station/slo-reporter#236](https://github.com/thoth-station/slo-reporter/issues/236)
> * [ ]  Add few mostly used stacks (check users or analyze some data from adviser reports [thoth-station/integration-tests#165](https://github.com/thoth-station/integration-tests/issues/165) ) to integrations-tests to pre-heat the cache
> * [ ]  document authenticated/non authenticated workflows and the req for a token, have a ADR like doc
> 

@fridex do you take care of last task?

> **Describe alternatives you've considered**
> Leave the services as they are.
> 
> **Additional context**
> 
> Related-To: #1025
> 
> @goern @harshad16 @fridex @KPostOffice

**Comment by pacospace** [comment]
See: https://github.com/thoth-station/integration-tests/issues/179 @goern @fridex @harshad16 @KPostOffice

**Comment by goern** [comment]
any conclusion on this?

/priority important-soon

**Comment by pacospace** [comment]
> any conclusion on this?
> 
> /priority important-soon

This is already in place, we need some documentation and decide if we want to ore heat some other stacks beside the one for the tutorial.

**Comment by pacospace** [comment]
Close this issue as it is resolved, moved the creation of doc for authenticated workflows to new issue.
